In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../../src')))
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../../scripts')))

In [3]:
from utils import *
from plottings import *

In [4]:
df_train = pd.read_csv('../../data/train_final.csv')

In [5]:
df_test = pd.read_csv('../../data/final_test.csv')

In [6]:
df_train

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,Month,Day,Is_Weekend,Days_to_Holiday,Days_after_Holiday,MonthPhase
0,1,5,2015-07-31,5263,555,1,1,0,1,2015,7,31,0,64,42,2
1,2,5,2015-07-31,6064,625,1,1,0,1,2015,7,31,0,64,42,2
2,3,5,2015-07-31,8314,821,1,1,0,1,2015,7,31,0,64,42,2
3,4,5,2015-07-31,13995,1498,1,1,0,1,2015,7,31,0,64,42,2
4,5,5,2015-07-31,4822,559,1,1,0,1,2015,7,31,0,64,42,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,1,1,2013,1,1,0,0,0,0
1017205,1112,2,2013-01-01,0,0,0,0,1,1,2013,1,1,0,0,0,0
1017206,1113,2,2013-01-01,0,0,0,0,1,1,2013,1,1,0,0,0,0
1017207,1114,2,2013-01-01,0,0,0,0,1,1,2013,1,1,0,0,0,0
1017208,1115,2,2013-01-01,0,0,0,0,1,1,2013,1,1,0,0,0,0

In [7]:
df_test

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,Year,Month,Day,Is_Weekend,Days_to_Holiday,Days_after_Holiday,MonthPhase
0,1,1,4,2015-09-17,1.0,1,0,0,2015,9,17,0,333,33.0,1
1,2,3,4,2015-09-17,1.0,1,0,0,2015,9,17,0,333,33.0,1
2,3,7,4,2015-09-17,1.0,1,0,0,2015,9,17,0,333,33.0,1
3,4,8,4,2015-09-17,1.0,1,0,0,2015,9,17,0,333,33.0,1
4,5,9,4,2015-09-17,1.0,1,0,0,2015,9,17,0,333,33.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0,2015,8,1,1,14,-1.0,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0,2015,8,1,1,14,-1.0,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0,2015,8,1,1,14,-1.0,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0,2015,8,1,1,14,-1.0,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1,2015,8,1,1,14,-1.0,0

In [8]:
df_train = df_train.drop(columns=['Date'])

In [9]:
df_test = df_test.drop(columns=['Date'])

In [11]:
column_summary(df_train)

,col_name,col_dtype,num_of_nulls,num_of_non_nulls,num_of_distinct_values,distinct_values_counts
0,Store,int64,0,1017209,1115,"{1: 942, 726: 942, 708: 942, 709: 942, 713: 94..."
1,DayOfWeek,int64,0,1017209,7,"{5: 145845, 4: 145845, 3: 145665, 2: 145664, 1..."
2,Sales,int64,0,1017209,21734,"{0: 172871, 5674: 215, 5558: 197, 5483: 196, 6..."
3,Customers,int64,0,1017209,4086,"{0: 172869, 560: 2414, 576: 2363, 603: 2337, 5..."
4,Open,int64,0,1017209,2,"{1: 844392, 0: 172817}"
5,Promo,int64,0,1017209,2,"{0: 629129, 1: 388080}"
6,StateHoliday,int64,0,1017209,4,"{0: 986159, 1: 20260, 2: 6690, 3: 4100}"
7,SchoolHoliday,int64,0,1017209,2,"{0: 835488, 1: 181721}"
8,Year,int64,0,1017209,3,"{2013: 406974, 2014: 373855, 2015: 236380}"
9,Month,int64,0,1017209,12,"{5: 103695, 3: 103695, 1: 103694, 6: 100350, 4..."
10,Day,int64,0,1017209,31,"{16: 33485, 17: 33485, 6: 33485, 7: 33485, 8: ..."
11,Is_Weekend,int64,0,1017209,2,"{0: 727749, 1: 289460}"
12,Days_to_Holiday,int64,0,1017209,106,"{0: 53194, 2: 45750, 1: 45750, 3: 40175, 4: 39..."
13,Days_after_Holiday,int64,0,1017209,87,"{0: 53194, 1: 47045, 2: 47045, 3: 41470, 4: 40..."
14,MonthPhase,int64,0,1017209,3,"{2: 347510, 1: 334850, 0: 334849}"

In [14]:
column_summary(df_test)

,col_name,col_dtype,num_of_nulls,num_of_non_nulls,num_of_distinct_values,distinct_values_counts
0,Id,int64,0,41088,41088,"{1: 1, 27446: 1, 27388: 1, 27389: 1, 27390: 1,..."
1,Store,int64,0,41088,856,"{1: 48, 727: 48, 729: 48, 731: 48, 732: 48, 73..."
2,DayOfWeek,int64,0,41088,7,"{4: 5992, 3: 5992, 2: 5992, 1: 5992, 7: 5992, ..."
3,Open,float64,0,41088,2,"{1.0: 35104, 0.0: 5984}"
4,Promo,int64,0,41088,2,"{0: 24824, 1: 16264}"
5,StateHoliday,int64,0,41088,2,"{0: 40908, 1: 180}"
6,SchoolHoliday,int64,0,41088,2,"{0: 22866, 1: 18222}"
7,Year,int64,0,41088,1,{2015: 41088}
8,Month,int64,0,41088,2,"{8: 26536, 9: 14552}"
9,Day,int64,0,41088,31,"{17: 1712, 8: 1712, 1: 1712, 16: 1712, 3: 1712..."
10,Is_Weekend,int64,0,41088,2,"{0: 29104, 1: 11984}"
11,Days_to_Holiday,int64,0,41088,48,"{333: 856, 334: 856, 359: 856, 360: 856, 361: ..."
12,Days_after_Holiday,float64,0,41088,35,"{-1.0: 11984, 7.0: 856, 13.0: 856, 12.0: 856, ..."
13,MonthPhase,int64,0,41088,3,"{0: 17120, 1: 14552, 2: 9416}"

## Scaling

In [17]:
columns_to_scale = [
     'Days_to_Holiday', 'Days_after_Holiday',
    'Day', 'Month', 'DayOfWeek', 'MonthPhase'
]

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the relevant columns and transform
df_train[columns_to_scale] = scaler.fit_transform(df_train[columns_to_scale])
df_test[columns_to_scale] = scaler.fit_transform(df_test[columns_to_scale])

# Training

In [33]:
X_train = df_train.drop(columns=['Sales'])
y_train = df_train['Sales']

In [35]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Scaling
    ('model', RandomForestRegressor(n_estimators=100, random_state=42))  # Random Forest
])

In [36]:
pipeline.fit(X_train, y_train)

MemoryError: could not allocate 33554432 bytes